# ESPHome configuration for M5C-0004
# Copyright © Stephen Irons 2026

# Hardware
# * M5Stick-C


substitutions:
  device_id: m5c-0004
  device_name: M5C-0004
  device_manufacturer: Ironspark
  device_part_number: 99-9001-0004-00
  device_model: M5Stick-C
  device_serial: 99-9001-0004
  device_uart: "/dev/serial/by-id/usb-Kongou_Hikari_M5Stack_Intf_9156038945-if00-port0"
  device_ipaddr: "192.168.1.124"
  device_hostname: m5c-0004.local
  device_uuid: 92bcad4d-d244-4a35-afb2-034afdc2f9a1

  ha_api_key: !secret m5c-0004-ha_api_key
  ota_password: !secret m5c-0004-ota_password
  ap_ssid: !secret m5c-0004-ap_ssid
  ap_psk: !secret m5c-0004-ap_psk
  tb_api_key: !secret m5c-0004-tb_api_key


esphome:
  name: ${device_id}
  friendly_name: ${device_name}
  platformio_options:
    upload_speed: 750000


esp32:
  board: m5stick-c
  framework:
    # External component axp192 requires arduino framework
    type: arduino


api:
  encryption:
    key: ${ha_api_key}


ota:
  - platform: esphome
    password: ${ota_password}


logger:


packages:
  core_hw: !include
    file: hw/m5stick-c.yaml

  firmware_details: !include
    file: shared/firmware_details.yaml

  common: !include
    file: shared/debug-heap.yaml

  wifi: !include
    file: shared/wifi.yaml

  fonts: !include
    file: fonts/fonts-m5stick.yaml


wifi:
  ap:
    ssid: ${ap_ssid}
    password: ${ap_psk}


binary_sensor:
  - id: !extend btn_A
    on_press:
      then:
        - light.toggle: light1

  - id: !extend btn_B
    on_press:
      then:
        - light.turn_on: light1
        - display.page.show_next: disp_A

    on_release:
      then:
        - light.turn_off: light1


light:
  - platform: monochromatic
    id: light1
    name: LED
    output: led1


time:
  - platform: homeassistant
    id: ha_time


display:
  - id: !extend disp_A
    pages:
      - !include
          file: pages-simple/page-diag.yaml
          vars:
            page_id: page_diag
            page_title: "Diagnostics"

      - !include
          file: pages-simple/page-wifi.yaml
          vars:
            page_id: page_wifi
            page_title: "Wi-Fi"

      - !include
          file: pages-simple/page-test.yaml
          vars:
            page_id: page_test
            page_title: "Text test page"
            test_text: "AGKMQRWXadibegjmqptwy"


interval:
  - interval: 10s
    then:
      - display.page.show_next: disp_A
      - component.update: disp_A


sensor:
  - platform: internal_temperature
    id: internal_temperature_C
    name: "Internal Temperature"
    update_interval: 15s

  - platform: wifi_signal
    id: wifi_level_dBm
    name: "WiFi level"
    update_interval: 15s


text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP address"
      id: wifi_ipaddr

    ssid:
      name: "SSID"
      id: wifi_ssid

    mac_address:
      name: "MAC"
      id: wifi_mac
