# ESPHome configuration for M5C-0003
# Copyright © Stephen Irons 2026

substitutions:
  device_id: m5c-0003
  device_name: M5C-0003
  device_manufacturer: Ironspark
  device_part_number: 99-9001-0004-00
  device_model: M5Stick-C
  device_serial: 99-9001-0003
  device_uart: "/dev/serial/by-id/usb-Kongou_Hikari_M5Stack_Intf_4152A0BD45-if00-port0"
  device_ipaddr: "192.168.1.123"
  device_hostname: m5c-0003.local
  device_uuid: 1dea6250-1f83-4351-8ecc-1b40b4ab219d

  ha_api_key: !secret m5c-0003-ha_api_key
  ota_password: !secret m5c-0003-ota_password
  ap_ssid: !secret m5c-0003-ap_ssid
  ap_psk: !secret m5c-0003-ap_psk


esphome:
  name: ${device_id}
  friendly_name: ${device_name}
  platformio_options:
    upload_speed: 750000


esp32:
  board: m5stick-c
  framework:
    # External component axp192 requires arduino framework
    type: arduino


api:
  encryption:
    key: ${ha_api_key}


ota:
  - platform: esphome
    password: ${ota_password}


logger:


packages:
  common: !include
    file: shared/debug.yaml

  wifi: !include
    file: shared/wifi.yaml

  fonts: !include
    file: fonts-m5stick.yaml


external_components:
  # AXP192 power management needed to turn TFT power on
  - source: github://martydingo/esphome-axp192
    components: [axp192]


wifi:
  ap:
    ssid: ${ap_ssid}
    password: ${ap_psk}


light:
  - platform: monochromatic
    output: builtin_led
    name: LED
    id: led1


output:
  - platform: ledc
    pin: GPIO10
    inverted: true
    id: builtin_led


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO37
      inverted: true
    name: Button A
    on_press:
      then:
        - light.toggle: led1

  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: Button B
    on_press:
      then:
        - light.turn_on: led1
    on_release:
      then:
        - light.turn_off: led1


spi:
  clk_pin: GPIO13
  mosi_pin: GPIO15


display:
  - platform: st7735
    model: "INITR_MINI160X80"
    reset_pin: GPIO18
    cs_pin: GPIO5
    dc_pin: GPIO23
    rotation: 270
    device_width: 80
    device_height: 160
    col_start: 26
    row_start: 1
    use_bgr: true
    invert_colors: true
    eight_bit_color: true
    update_interval: 10s

    id: disp_1
    pages:
      - id: page_diagnostics
        lambda: |-
          it.printf(2, 16, id(heading), TextAlign::BASELINE_LEFT, "Diagnostics");

          it.printf(2, 31, id(text_normal), TextAlign::BASELINE_LEFT, "RSSI");
          it.printf(120, 31, id(text_bold), TextAlign::BASELINE_RIGHT, "%.1f", id(wifi_dBm).state);
          it.printf(128, 31, id(text_normal), TextAlign::BASELINE_LEFT, "dBm");

          it.printf(2, 46, id(text_normal), TextAlign::BASELINE_LEFT, "Battery");
          it.printf(120, 46, id(text_bold), TextAlign::BASELINE_RIGHT, "%.1f", id(battery_level_pc).state);
          it.printf(128, 46, id(text_normal), TextAlign::BASELINE_LEFT, "%%");

          it.printf(2, 61, id(text_normal), TextAlign::BASELINE_LEFT, "Uptime");
          it.printf(120, 61, id(text_bold), TextAlign::BASELINE_RIGHT, "%.1f", id(uptime_s).state/3600);
          it.printf(128, 61, id(text_normal), TextAlign::BASELINE_LEFT, "h");

          it.printf(2, 76, id(text_normal), TextAlign::BASELINE_LEFT, "Line 4");

      - id: page_wifi
        lambda: |-
          it.printf(2, 20, id(heading), TextAlign::BASELINE_LEFT, "Page 2");


interval:
  - interval: 5s
    then:
      - display.page.show_next: disp_1
      - component.update: disp_1


i2c:
  - id: bus_a
    sda: GPIO21
    scl: GPIO22
    scan: true


sensor:
  - platform: axp192
    model: M5STICKC
    address: 0x34
    i2c_id: bus_a
    update_interval: 30s
    battery_level:
      name: "Battery Level"
      id: "battery_level_pc"

  - platform: wifi_signal
    name: WiFi Level
    id: wifi_dBm
