# ESPHome configuration for host-stick-c
# Copyright © Stephen Irons 2026

# Hardware
# * Host


substitutions:
  device_id: m5c-9001
  device_name: M5C-9001
  device_manufacturer: Ironspark
  device_part_number: 99-9001-0009-00
  device_model: M5Stick-C
  device_serial: 99-9001-9001
  #device_uart: "/dev/serial/by-id/usb-Kongou_Hikari_M5Stack_Intf_4152A0BD45-if00-port0"
  #device_ipaddr: "192.168.1.123"
  #device_hostname: m5c-0003.local
  device_uuid: 611673ff-b3f4-4d1f-ad17-8e10d56c2327

  ha_api_key: !secret m5c-9001-ha_api_key
  ota_password: !secret m5c-9001-ota_password
  ap_ssid: !secret m5c-9001-ap_ssid
  ap_psk: !secret m5c-9001-ap_psk
  tb_api_key: !secret m5c-9001-tb_api_key


esphome:
  name: ${device_id}
  friendly_name: ${device_name}


api:
  encryption:
    key: ${ha_api_key}


logger:


packages:
  core_hw: !include
    file: hw/host_sdl.yaml
    vars:
      display_width: 160
      display_height: 80

  firmware_details: !include
    file: shared/firmware_details.yaml

  common: !include
    file: shared/debug-heap.yaml

  fonts: !include
    file: fonts/fonts-m5stick.yaml


binary_sensor:
  - id: !extend btn_A
    on_press:
      then:
        - display.page.show_next: disp_A
        - component.update: disp_A


display:
  - id: !extend disp_A
    pages:
      - !include
          file: pages-simple/page-diag.yaml
          vars:
            page_id: page_diag
            page_title: "Diagnostics"

      - !include
          file: pages-simple/page-test.yaml
          vars:
            page_id: page_test
            page_title: "Text test page"
            test_text: "AGKMQQRWXadibejgjmqptwy"


interval:
  - interval: 60s
    then:
      - display.page.show_next: disp_A
      - component.update: disp_A
