# ESPHome configuration for M5C-0004
# Copyright © Stephen Irons 2026

# Hardware
# * M5Stick-C


substitutions:
  device_id: m5c-0004
  device_name: M5C-0004
  device_manufacturer: Ironspark
  device_part_number: 99-9001-0004-00
  device_model: M5Stick-C
  device_serial: 99-9001-0004
  device_uart: "/dev/serial/by-id/usb-Kongou_Hikari_M5Stack_Intf_9156038945-if00-port0"
  device_ipaddr: "192.168.1.124"
  device_hostname: m5c-0004.local
  device_uuid: 92bcad4d-d244-4a35-afb2-034afdc2f9a1

  ha_api_key: !secret m5c-0004-ha_api_key
  ota_password: !secret m5c-0004-ota_password
  ap_ssid: !secret m5c-0004-ap_ssid
  ap_psk: !secret m5c-0004-ap_psk


esphome:
  name: ${device_id}
  friendly_name: ${device_name}
  platformio_options:
    upload_speed: 750000


esp32:
  board: m5stick-c
  framework:
    # External component axp192 requires arduino framework
    type: arduino


api:
  encryption:
    key: ${ha_api_key}


ota:
  - platform: esphome
    password: ${ota_password}


logger:


packages:
  core_hw: !include
    file: hw/m5stick-c.yaml

  common: !include
    file: shared/debug.yaml

  wifi: !include
    file: shared/wifi.yaml

  fonts: !include
    file: fonts-m5stick.yaml


wifi:
  ap:
    ssid: ${ap_ssid}
    password: ${ap_psk}


binary_sensor:
  - id: !extend btn_A
    on_press:
      then:
        - light.toggle: light1

  - id: !extend btn_B
    on_press:
      then:
        - light.turn_on: light1
    on_release:
      then:
        - light.turn_off: light1


light:
  - platform: monochromatic
    id: light1
    name: LED
    output: led1


sensor:
  - platform: wifi_signal
    name: WiFi Level
    id: wifi_dBm
    update_interval: 30s


text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP address"

    ssid:
      name: "SSID"

    mac_address:
      name: "MAC"


time:
  - platform: homeassistant
    id: ha_time


display:
  - id: !extend disp_A
    pages:
      - id: page_diagnostics
        lambda: |-
          it.printf(2, 16, id(heading), TextAlign::BASELINE_LEFT, "Diagnostics");

          it.printf(2, 31, id(text_normal), TextAlign::BASELINE_LEFT, "RSSI");
          it.printf(120, 31, id(text_bold), TextAlign::BASELINE_RIGHT, "%.1f", id(wifi_dBm).state);
          it.printf(128, 31, id(text_normal), TextAlign::BASELINE_LEFT, "dBm");

          it.printf(2, 46, id(text_normal), TextAlign::BASELINE_LEFT, "Battery");
          it.printf(120, 46, id(text_bold), TextAlign::BASELINE_RIGHT, "%.1f", id(battery_level_pc).state);
          it.printf(128, 46, id(text_normal), TextAlign::BASELINE_LEFT, "%%");

          it.printf(2, 61, id(text_normal), TextAlign::BASELINE_LEFT, "Uptime");
          it.printf(120, 61, id(text_bold), TextAlign::BASELINE_RIGHT, "%.1f", id(uptime_s).state/3600);
          it.printf(128, 61, id(text_normal), TextAlign::BASELINE_LEFT, "h");

          it.printf(2, 76, id(text_normal), TextAlign::BASELINE_LEFT, "Line 4");

      - id: page_wifi
        lambda: |-
          it.printf(2, 20, id(heading), TextAlign::BASELINE_LEFT, "Page 2");


interval:
  - interval: 5s
    then:
      - display.page.show_next: disp_A
      - component.update: disp_A
