# ESPHome configuration for M5C-0003
# Copyright © Stephen Irons 2026

# Hardware
# * M5Stick-C


substitutions:
  device_id: m5c-0003
  device_name: M5C-0003
  device_manufacturer: Ironspark
  device_part_number: 99-9001-0004-00
  device_model: M5Stick-C
  device_serial: 99-9001-0003
  device_uart: "/dev/serial/by-id/usb-Kongou_Hikari_M5Stack_Intf_4152A0BD45-if00-port0"
  device_ipaddr: "192.168.1.123"
  device_hostname: m5c-0003.local
  device_uuid: 1dea6250-1f83-4351-8ecc-1b40b4ab219d

  ha_api_key: !secret m5c-0003-ha_api_key
  ota_password: !secret m5c-0003-ota_password
  ap_ssid: !secret m5c-0003-ap_ssid
  ap_psk: !secret m5c-0003-ap_psk
  tb_api_key: !secret m5c-0003-tb_api_key


esphome:
  name: ${device_id}
  friendly_name: ${device_name}
  platformio_options:
    upload_speed: 750000


esp32:
  board: m5stick-c
  framework:
    # External component axp192 requires arduino framework
    type: arduino


api:
  encryption:
    key: ${ha_api_key}


ota:
  - platform: esphome
    password: ${ota_password}


logger:


packages:
  core_hw: !include
    file: hw/m5stick-c.yaml

  common: !include
    file: shared/debug.yaml

  wifi: !include
    file: shared/wifi.yaml

  fonts: !include
    file: fonts-m5stick.yaml


wifi:
  ap:
    ssid: ${ap_ssid}
    password: ${ap_psk}


binary_sensor:
  - id: !extend btn_A
    on_press:
      then:
        - light.toggle: light1

  - id: !extend btn_B
    on_press:
      then:
        - light.turn_on: light1
    on_release:
      then:
        - light.turn_off: light1


light:
  - platform: monochromatic
    id: light1
    name: LED
    output: led1


sensor:
  - platform: wifi_signal
    name: WiFi Level
    id: wifi_dBm
    update_interval: 30s


text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP address"
      id: wifi_ip_addr

    ssid:
      name: "SSID"
      id: wifi_ssid

    mac_address:
      name: "MAC"
      id: wifi_mac


time:
  - platform: homeassistant
    id: ha_time


display:
  - id: !extend disp_A
    pages:
      - !include
          file: page-diag-simple.yaml
          vars:
            page_id: page_diag
            page_title: "Diagnostics"

      - !include
          file: page-wifi-simple.yaml
          vars:
            page_id: page_wifi
            page_title: "Wi-Fi"


interval:
  - interval: 5s
    then:
      - display.page.show_next: disp_A
      - component.update: disp_A
