esphome:
  name: m5d-0006
  on_boot:
    then:
      - pcf8563.read_time:
  platformio_options:
    board_build.flash_mode: dio

esp32:
  variant: esp32s3
  framework:
    type: esp-idf

wifi:
  networks:
    - ssid: "ioSphere dev"
      password: !secret "wifi_psk_ioSphere dev"
        
    - ssid: "wodexitose"
      password: !secret "wifi_psk_wodexitose"

captive_portal:


api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password


logger:

i2c:
  - id: internal_i2c
    sda: GPIO11
    scl: GPIO12

rc522_i2c:
  - id: nfc_reader
    i2c_id: internal_i2c
    address: 0x28
    on_tag:
      then:
        - rtttl.play: "scan-success:d=4,o=5,b=120:32c,32g,32b"
        - light.turn_on: display_backlight
        - homeassistant.tag_scanned: !lambda 'return x;'

output:
  - platform: ledc
    pin: GPIO3
    id: buzzer

  - platform: ledc
    pin: GPIO9
    id: backlight_output

rtttl:
  output: buzzer

sensor:
  - platform: rotary_encoder
    id: encoder
    name: Encoder
    pin_a: GPIO40
    pin_b: GPIO41

time:
  # RTC
  - platform: pcf8563
    id: rtctime
    i2c_id: internal_i2c
    address: 0x51
    update_interval: never

  - platform: homeassistant
    id: esptime
    on_time_sync:
      then:
        - pcf8563.write_time:

binary_sensor:
  - platform: gpio
    name: Button
    id: front_button
    pin: GPIO42
    filters:
      - invert:

spi:
  id: spi_bus
  mosi_pin: GPIO5
  clk_pin: GPIO6

display:
  - platform: ili9xxx
    id: round_display
    model: GC9A01A
    cs_pin: GPIO7
    reset_pin: GPIO8
    dc_pin: GPIO4
    invert_colors: false

touchscreen:
  - platform: ft5x06
    id: touch
    i2c_id: internal_i2c
    address: 0x38
    # interrupt_pin: GPIO14  # not supported by this component

light:
  - platform: monochromatic
    name: "Backlight"
    output: backlight_output
    id: display_backlight
    default_transition_length: 1s
    on_turn_on:
      then:
        - delay: 5s
        - light.turn_off: display_backlight

