# ESPHome configuration for M5D-0006
# Copyright © Stephen Irons 2026

# Hardware
# * M5Dial


substitutions:
  device_id: m5d-0006
  device_name: M5D-0006
  device_manufacturer: Ironspark
  device_part_number: 99-9001-0002-00
  device_model: M5Dial
  device_serial: 99-9001-0006
  device_uart: "/dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_C0:4E:30:12:AF:94-if00"
  device_ipaddr: "192.168.1.126"
  device_hostname: m5d-0006.local
  device_uuid: d16a1546-bea3-409c-8c0d-46213c581849

  ha_api_key: !secret m5d-0006-ha_api_key
  ota_password: !secret m5d-0006-ota_password
  ap_ssid: !secret m5d-0006-ap_ssid
  ap_psk: !secret m5d-0006-ap_psk


esphome:
  name: ${device_id}
  friendly_name: ${device_name}
  platformio_options:
    board_build.flash_mode: dio

  on_boot:
    then:
      - pcf8563.read_time:


esp32:
  variant: esp32s3
  framework:
    type: esp-idf


api:
  encryption:
    key: ${ha_api_key}


ota:
  - platform: esphome
    password: ${ota_password}


logger:


packages:
  core_hw: !include
    file: hw/m5dial.yaml

  common: !include
    file: shared/debug.yaml

  wifi: !include
    file: shared/wifi.yaml

  fonts: !include
    file: fonts-m5stick.yaml


wifi:
  ap:
    ssid: ${ap_ssid}
    password: ${ap_psk}


rc522_i2c:
  - id: !extend nfc_reader
    on_tag:
      then:
        - globals.set:
            id: tag_id
            value: !lambda 'return x;'
        - globals.set:
            id: tag_result
            value: !lambda 'if (x == "2A-71-23-3A") return "OK"; else return "No";'
        - display.page.show: page_scan
        - component.update: disp_A
        - light.turn_on: display_backlight
        - if:
            condition:
                lambda: 'return id(tag_result) == "OK";'
            then:
              rtttl.play: "scan-allow:d=4,o=5,b=120:32c,32g,32b"
            else:
              rtttl.play: "scan-deny:d=4,o=5,b=120:8c4"

        - homeassistant.tag_scanned: !lambda 'return x;'


rtttl:
  output: buzzer


time:
  - platform: homeassistant
    id: esptime
    on_time_sync:
      then:
        - pcf8563.write_time:


#      - id: page_wifi
#        lambda: |-
#          it.printf(2, 16, id(heading), TextAlign::BASELINE_LEFT, "Page 2");


#interval:
#  - interval: 5s
#    then:
#      - display.page.show_next: disp_1
#      - component.update: disp_1


light:
  - platform: monochromatic
    name: "Backlight"
    output: backlight_output
    id: display_backlight
    default_transition_length: 1s
    on_turn_on:
      then:
        - delay: 5s
        - light.turn_off: display_backlight


globals:
  - id: tag_id
    type: std::string
    restore_value: no
    # max_restore_data_length: 24
    initial_value: '"---"'

  - id: tag_result
    type: std::string
    restore_value: no
    # max_restore_data_length: 24
    initial_value: '"--"'


display:
  - id: !extend disp_A
    pages:
      - !include
          file: page-diag-simple.yaml
          vars:
            page_id: page_diag
            page_title: "Diagnostics"

      - !include
          file: page-scan-simple.yaml
          vars:
            page_id: page_scan
            page_title: "Scan"
