# ESPHome configuration for M5S-0001
# Copyright © Stephen Irons 2026

# Hardware
# * M5RELAY

substitutions:
  device_id: m5s-0005
  device_name: M5S-0005
  device_manufacturer: Ironspark
  device_part_number: 99-9001-0012-00
  device_model: M5RELAY-1
  device_serial: 99-9001-0005
  device_uart: "/dev/serial/by-id/usb-Silicon_Labs_CP2104_USB_to_UART_Bridge_Controller_01BB98C0-if00-port0"
  device_ipaddr: "192.168.1.125"
  device_hostname: m5s-0005.local
  device_uuid: db3fc64b-6dab-4623-a621-32026a754518

  ha_api_key: !secret m5s-0005-ha_api_key
  ota_password: !secret m5s-0005-ota_password
  ap_ssid: !secret m5s-0005-ap_ssid
  ap_psk: !secret m5s-0005-ap_psk
  http_api_key1: !secret m5s-0005-tb_api_key


esphome:
  name: ${device_id}
  friendly_name: ${device_name}
  on_boot:
    then:
      - output.turn_on:
          id: lcd_bl

      - output.set_level:
          id: lcd_bl
          level: 100%


esp32:
  board: m5stack-core-esp32
  framework:
    type: esp-idf


api:
  encryption:
    key: ${ha_api_key}


ota:
  - platform: esphome
    password: ${ota_password}


logger:


packages:
  m5core: !include
    file: m5stack-core.yaml
    vars:
      invert_colors: false

  m5base: !include
    file: m5stack-relay.yaml

  common: !include
    file: shared/debug.yaml

  wifi: !include
    file: shared/wifi.yaml

  fonts: !include
    file: fonts-m5stack.yaml


wifi:
  ap:
    ssid: ${ap_ssid}
    password: ${ap_psk}

  on_connect:
    then:
      - lvgl.label.update:
          id: page_wifi_value_state
          text: "Connected"

  on_disconnect:
    then:
      - lvgl.label.update:
          id: page_wifi_value_state
          text: "Disconnected"
      - lvgl.label.update:
          id: page_wifi_value_ssid
          text: " "
      - lvgl.label.update:
          id: page_wifi_value_rssi
          text: "--"
      - lvgl.label.update:
          id: page_wifi_value_ipaddr
          text: " "


time:
  - platform: homeassistant
    id: ha_time


text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP address"
      on_value:
        then:
          - lvgl.label.update:
              id: page_wifi_value_ipaddr
              text:
                format: "%s"
                args:
                  - x.c_str()
    ssid:
      name: "SSID"
      on_value:
        then:
          - lvgl.label.update:
              id: page_wifi_value_ssid
              text:
                format: "%s"
                args:
                  - x.c_str()
    mac_address:
      name: "MAC"
      on_value:
        then:
          - lvgl.label.update:
              id: page_wifi_value_macaddr
              text:
                format: "%s"
                args:
                  - x.c_str()


sensor:
  - platform: wifi_signal
    name: "WiFi signal sensor"
    update_interval: 30s
    on_value:
      then:
        - lvgl.label.update:
            id: page_wifi_value_rssi
            text:
              format: "%.1f"
              args:
                - x


binary_sensor:
  - id: !extend btn_A
    on_press:
      then:
        - output.turn_on: rly_A
    on_release:
      then:
        - output.turn_off: rly_A

  - id: !extend btn_B
    on_press:
      then:
        - output.turn_on: rly_B
    on_release:
      then:
        - output.turn_off: rly_B

  - id: !extend btn_C
    on_press:
      then:
        - lvgl.page.next:


lvgl:
  displays:
    - lcd_A
  buffer_size: 8%
  pages:
    - !include
        file: page_wifi.yaml
        vars:
          page_id: page_wifi
          page_title: "Wi-Fi"
