substitutions:
  http_api_key: !secret http_api_key

esphome:
  name: m5s-0001
  on_boot:
    then:
      - output.turn_on:
          id: lcd_bl
      - output.set_level:
          id: lcd_bl
          level: 100%

packages:
  core_hw: !include 
    file: m5stack-core.yaml
    vars:
      invert_colors: true

  lps_hw: !include
    file: lps22.yaml
    vars:
      lps22_id: lps22_A
      lps22_name: LPS22.A
      lps22_i2c_addr: 0x5D  

  rx_hw: !include
    file: m5stack-lora433-ook.yaml
    vars:
      rx_id: rx_A
      rx_name: RX.A
      rx_OOK_pin: GPIO13
      rx_frequency: 433920000
       
  wx: !include
    file: wx-433.yaml
    vars:
      wx_id: wx_A
      wx_name: WX.A
      rx_id: rx_A
      wx_tx_model: "Fineoffset-WHx080"
      wx_tx_id: 87
      
  fonts: !include
    file: fonts-m5stack.yaml
    

esp32:
  board: m5stack-core-esp32
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_MBEDTLS_CERTIFICATE_BUNDLE: y

#     type: arduino


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password


wifi:
  fast_connect: true
  enable_btm: true
  enable_rrm: true

  networks:
    - ssid: "wodexisixes-6"
      password: !secret "wifi_psk_wodexisixes-6"

    - ssid: "ioSphere dev"
      password: !secret "wifi_psk_ioSphere dev"
        
    - ssid: "wodexitose"
      password: !secret "wifi_psk_wodexitose"

  on_connect:
    then:
      - lvgl.label.update:
          id: page_wifi_value_state
          text: "Connected"

  on_disconnect:
    then:
      - lvgl.label.update:
          id: page_wifi_value_state
          text: "Disconnected"
      - lvgl.label.update:
          id: page_wifi_value_ssid
          text: " "
      - lvgl.label.update:
          id: page_wifi_value_rssi
          text: "--"
      - lvgl.label.update:
          id: page_wifi_value_ipaddr
          text: " "

debug:
  update_interval: 10s

time:
  - platform: homeassistant
    id: ha_time


http_request:
  timeout: 10s
  watchdog_timeout: 20s


#mqtt:
#  id: mqtt_tb
#  broker: iot.irons.nz
#  port: 1883
#  username: !secret mqtt_tb_token
#  reboot_timeout: 0s
#  topic_prefix: null
#  keepalive: 30s
#  idf_send_async: true
#  discovery: false
#  discover_ip: false
#  discovery_retain: false


text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP address"
      on_value:
        then:
          - lvgl.label.update:
              id: page_wifi_value_ipaddr
              text:
                format: "%s"
                args:
                  - x.c_str()
    ssid:
      name: "SSID"
      on_value:
        then:
          - lvgl.label.update:
              id: page_wifi_value_ssid
              text:
                format: "%s"
                args:
                  - x.c_str()
    mac_address:
      name: "MAC"


sensor:
  - id: !extend lps22_A
    temperature:
      on_value:
        - lvgl.label.update:
            id: page_wx_value_temperature_in
            text:
              format: "%.1f"
              args:
                - x
    pressure:
      on_value:
        then:
          - lvgl.label.update:
              id: page_wx_value_pressure
              text:
                format: "%.1f"
                args:
                  - x

          - if:
              condition:
                and:
                  - time.has_time:
                      id: ha_time
                  - wifi.connected:
              then:
#                - mqtt.publish_json:
#                    topic: "v1/devices/me/telemetry"
#                    qos: 1
#                    payload: |-
#                      root["ts"] = id(ha_time).now().timestamp * 1000;
#                      JsonObject values = root["values"].to<JsonObject>();
#                      values["mqtt_pressure"] = x;
#                      values["mqtt_other"] = x * 2.0;

                - http_request.post:
                    url: https://iot.irons.nz/api/v1/${http_api_key}/telemetry
                    request_headers:
                      Content-Type: application/json
                    json: |-
                      root["ts"] = id(ha_time).now().timestamp * 1000;
                      JsonObject values = root["values"].to<JsonObject>();
                      values["http_pressure"] = x;
                      values["http_other"] = x * 3.0;

#          - lambda: |-
#              if (id(ha_time).now().is_valid()) {
#                id(mqtt_tb).publish_json("v1/devices/me/telemetry", [=](JsonObject root) {
#                  root["ts"] = id(ha_time).now().timestamp * 1000;
#                  root["values"]["pressure"] = x;
#                });
#              };

  # WX.A temperature
  - id: !extend wx_A_temperature
    on_value:
      - lvgl.label.update:
          id: page_wx_value_temperature
          text:
            format: "%.1f"
            args:
              - x
  
  # WX.A humidity
  - id: !extend wx_A_humidity
    on_value:
      - lvgl.label.update:
          id: page_wx_value_humidity
          text:
            format: "%.1f"
            args:
              - x
    
  # WX.A rain
  - id: !extend wx_A_rain_total
#    on_value:
#      - lvgl.label.update:
#          id: page_wx_value_rain_total
#          text:
#            format: "%.1f"
#            args:
#              - x

  - id: !extend wx_A_rain_5min
#    on_value:
#      - lvgl.label.update:
#          id: page_wx_value_rain_5min
#          text:
#            format: "%.1f"
#            args:
#              - x

  - id: !extend wx_A_rain_1h
    on_value:
      - lvgl.label.update:
          id: page_wx_value_rain_1h
          text:
            format: "%.1f"
            args:
              - x

  - id: !extend wx_A_rain_24h
    on_value:
      - lvgl.label.update:
          id: page_wx_value_rain_24h
          text:
            format: "%.1f"
            args:
              - x

  # WX.A wind speed
  - id: !extend wx_A_wind_avg
    on_value:
      - lvgl.label.update:
          id: page_wx_value_wind_speed_m_s
          text:
            format: "%.1f"
            args:
              - x
      - lvgl.label.update:
          id: page_wx_value_wind_speed_kn
          text:
            format: "%.1f"
            args:
              - !lambda x * 1.944

  - id: !extend wx_A_wind_max

  # WX.A wind direction
  - id: !extend wx_A_wind_dir
    
  - id: !extend wx_A_wind_dir_smooth
    on_value:
      - lvgl.label.update:
          id: page_wx_value_wind_dir
          text:
            format: "%.1f"
            args:
              - x

  # Wi-Fi
  - platform: wifi_signal
    name: "WiFi signal sensor"
    update_interval: 10s
    on_value:
      then:
        - lvgl.label.update:
            id: page_wifi_value_rssi
            text:
              format: "%.1f"
              args:
                - x

  - platform: debug
    free:
      name: "Heap free"
    fragmentation:
      name: "Heap fragmentation"
    block:
      name: "Heap max block"
    loop_time:
      name: "Loop time"


binary_sensor:
  - id: !extend btn_C
    on_press:
      then:
        - lvgl.page.next:


lvgl:
  displays:
    - lcd_A
  buffer_size: 8%
  pages:
    - !include
        file: page_wx.yaml
        vars:
          page_id: page_wx
          page_title: "Weather"

    - !include
        file: page_wifi.yaml
        vars:
          page_id: page_wifi
          page_title: "Wi-Fi"

