esphome:
  name: m5s-0001
  on_boot:
    then:
      - output.turn_on:
          id: lcd_bl
      - output.set_level:
          id: lcd_bl
          level: 100%

packages:
    core: !include m5stack-core.yaml
    rtl_433: github://juanboro/esphome-rtl_433-decoder/rtl_433.yaml

esp32:
  board: m5stack-core-esp32
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password


wifi:
  networks:
    - ssid: "ioSphere dev"
      password: !secret "wifi_psk_ioSphere dev"
      manual_ip:
        static_ip: 192.168.1.161
        gateway: 192.168.1.1
        subnet: 255.255.255.0
        
    - ssid: "wodexitose"
      password: !secret "wifi_psk_wodexitose"


sensor:
  - platform: lps22
    address: 0x5D
    temperature:
      name: "LPS22 temperature"
      on_value:
        - lvgl.label.update:
            id: page_wx_temperature_inside
            text:
              format: "%.1f"
              args:
                - x
    pressure:
      name: "LPS22 pressure"
      on_value:
        - lvgl.label.update:
            id: page_wx_pressure
            text:
              format: "%.1f"
              args:
                - x

  - platform: template
    name: "WX temperature"
    id: wx_temperature
    unit_of_measurement: "°C"
    icon: "mdi:thermometer" 
    on_value:
      - lvgl.label.update:
          id: page_wx_temperature
          text:
            format: "%.1f"
            args:
              - x
    
  - platform: template
    name: "WX humidity"
    id: wx_humidity
    unit_of_measurement: "%RH"
    icon: "mdi:water-percent"
    
  - platform: template
    name: "WX rain"
    id: wx_rain
    unit_of_measurement: "mm"
    icon: "mdi:water"

  - platform: template
    name: "WX wind direction"
    id: wx_wind_dir
    unit_of_measurement: "°"
    icon: "mdi:compass"
    
  - platform: template
    name: "WX wind average"
    id: wx_wind_avg
    unit_of_measurement: "m.s-1"
    icon: "mdi:weather-windy"

  - platform: template
    name: "WX wind max"
    id: wx_wind_max
    unit_of_measurement: "m.s-1"
    icon: "mdi:weather-windy"
        

sx127x:
  cs_pin: GPIO05
  rst_pin: GPIO26
  dio0_pin: GPIO36
  frequency: 433920000
  bandwidth: 50_0kHz
  modulation: OOK
  rx_start: true
  packet_mode: false
  bitsync: true
  bitrate: 4800
  rx_floor: -90

remote_receiver:
  - pin: GPIO13
    id: rf_A

rtl_433:
  id: rtl_A
  receiver_id: rf_A
  on_json_message:
    then:
      - lambda: |-
          if ((x["model"] == "Fineoffset-WHx080") && (x["id"].as<int>() == 87)) {
            id(wx_temperature).publish_state(x["temperature_C"].as<float>());
            id(wx_humidity).publish_state(x["humidity"].as<float>());
            id(wx_rain).publish_state(x["rain_mm"].as<float>());
            id(wx_wind_dir).publish_state(x["wind_dir_deg"].as<float>());
            id(wx_wind_avg).publish_state(x["wind_avg_km_h"].as<float>()*0.278);
            id(wx_wind_max).publish_state(x["wind_max_km_h"].as<float>()*0.278);
          }


lvgl:
  displays:
    - lcd_A
  pages:
    - id: page_wx
      layout:
        type: grid
        grid_rows: [ content, content, content, content ]
        grid_columns: [ content, content, content ]
      widgets:
        - label:
            grid_cell_row_pos: 0
            grid_cell_column_pos: 0
            grid_cell_column_span: 3
            text: "Weather"
            text_align: LEFT
            text_font: heading

        - label:
            grid_cell_row_pos: 1
            grid_cell_column_pos: 0
            text: "Temperature"
            text_align: LEFT
            text_font: text_normal
        - label:
            id: page_wx_temperature
            grid_cell_row_pos: 1
            grid_cell_column_pos: 1
            text: "--"
            text_align: RIGHT
            text_font: text_bold
        - label:
            grid_cell_row_pos: 1
            grid_cell_column_pos: 2
            text: "°C"
            text_align: LEFT
            text_font: text_normal

        - label:
            grid_cell_row_pos: 2
            grid_cell_column_pos: 0
            text: "Pressure"
            text_align: LEFT
            text_font: text_normal
        - label:
            id: page_wx_pressure
            grid_cell_row_pos: 2
            grid_cell_column_pos: 1
            text: "--"
            text_align: RIGHT
            text_font: text_bold
        - label:
            grid_cell_row_pos: 2
            grid_cell_column_pos: 2
            text: "°C"
            text_align: LEFT
            text_font: text_normal

        - label:
            grid_cell_row_pos: 3
            grid_cell_column_pos: 0
            text: "Temperature in"
            text_align: LEFT
            text_font: text_normal
        - label:
            id: page_wx_temperature_inside
            grid_cell_row_pos: 3
            grid_cell_column_pos: 1
            text: "--"
            text_align: RIGHT
            text_font: text_bold
        - label:
            grid_cell_row_pos: 3
            grid_cell_column_pos: 2
            text: "°C"
            text_align: LEFT
            text_font: text_normal


font:
  - file: "fonts/bdf/75dpi/helvR14.bdf"
    id: text_normal

  - file: "fonts/bdf/75dpi/helvB14.bdf"
    id: text_bold

  - file: "fonts/bdf/75dpi/helvB18.bdf"
    id: heading

  - file: "fonts/bdf/75dpi/helvR10.bdf"
    id: text_tiny

