esphome:
  name: m5s-0001
  on_boot:
    then:
      - output.turn_on:
          id: lcd_bl
      - output.set_level:
          id: lcd_bl
          level: 100%

packages:
    core: !include m5stack-core.yaml
    rtl_433: github://juanboro/esphome-rtl_433-decoder/rtl_433.yaml

esp32:
  board: m5stack-core-esp32
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password


wifi:
  networks:
    - ssid: "ioSphere dev"
      password: !secret "wifi_psk_ioSphere dev"
      manual_ip:
        static_ip: 192.168.1.161
        gateway: 192.168.1.1
        subnet: 255.255.255.0
        
    - ssid: "wodexitose"
      password: !secret "wifi_psk_wodexitose"


sensor:
  - platform: lps22
    address: 0x5D
    temperature:
      name: "LPS22 temperature"
      accuracy_decimals: 1
      on_value:
        - lvgl.label.update:
            id: page_wx_value_temperature_in
            text:
              format: "%.1f"
              args:
                - x
    pressure:
      name: "LPS22 pressure"
      accuracy_decimals: 1
      on_value:
        - lvgl.label.update:
            id: page_wx_value_pressure
            text:
              format: "%.1f"
              args:
                - x

  - platform: template
    name: "WX temperature"
    id: wx_temperature
    accuracy_decimals: 1
    unit_of_measurement: "°C"
    icon: "mdi:thermometer" 
    on_value:
      - lvgl.label.update:
          id: page_wx_value_temperature
          text:
            format: "%.1f"
            args:
              - x
    
  - platform: template
    name: "WX humidity"
    id: wx_humidity
    accuracy_decimals: 1
    unit_of_measurement: "%RH"
    icon: "mdi:water-percent"
    on_value:
      - lvgl.label.update:
          id: page_wx_value_humidity
          text:
            format: "%.1f"
            args:
              - x
    
    
  - platform: template
    name: "WX rain total"
    id: wx_rain_total
    accuracy_decimals: 1
    unit_of_measurement: "mm"
    icon: "mdi:water"
#    on_value:
#      - lvgl.label.update:
#          id: page_wx_value_rain_total
#          text:
#            format: "%.1f"
#            args:
#              - x

  - platform: template
    name: "WX rain 05min"
    id: wx_rain_5min
    accuracy_decimals: 1
    unit_of_measurement: "mm"
    icon: "mdi:water"
    filters:
      - heartbeat: 30s
      - delay_delta:
          window_size: 10
    on_value:
      - lvgl.label.update:
          id: page_wx_value_rain_5min
          text:
            format: "%.1f"
            args:
              - x

  - platform: template
    name: "WX rain 1h"
    id: wx_rain_1h
    accuracy_decimals: 1
    unit_of_measurement: "mm"
    icon: "mdi:water"
    filters:
      - heartbeat: 5min
      - delay_delta:
          window_size: 12
    on_value:
      - lvgl.label.update:
          id: page_wx_value_rain_1h
          text:
            format: "%.1f"
            args:
              - x

  - platform: template
    name: "WX rain 24h"
    id: wx_rain_24h
    accuracy_decimals: 1
    unit_of_measurement: "mm"
    icon: "mdi:water"
    filters:
      - heartbeat: 5min
      - delay_delta:
          window_size: 288
    on_value:
      - lvgl.label.update:
          id: page_wx_value_rain_24h
          text:
            format: "%.1f"
            args:
              - x

  - platform: template
    name: "WX wind direction"
    id: wx_wind_dir
    accuracy_decimals: 1
    unit_of_measurement: "°"
    icon: "mdi:compass"
    
  - platform: template
    name: "WX wind average"
    id: wx_wind_avg
    accuracy_decimals: 1
    unit_of_measurement: "m.s-1"
    icon: "mdi:weather-windy"
    on_value:
      - lvgl.label.update:
          id: page_wx_value_wind_speed_m_s
          text:
            format: "%.1f"
            args:
              - x
      - lvgl.label.update:
          id: page_wx_value_wind_speed_kn
          text:
            format: "%.1f"
            args:
              - !lambda x * 1.944

  - platform: template
    name: "WX wind max"
    id: wx_wind_max
    accuracy_decimals: 1
    unit_of_measurement: "m.s-1"
    icon: "mdi:weather-windy"

  - platform: template
    name: "WX wind vector N smooth"
    id: wx_wind_n_smooth
    accuracy_decimals: 3
    unit_of_measurement: ""
    filters:
      exponential_moving_average:
        alpha: 0.1
        send_every: 1
        send_first_at: 1
            
  - platform: template
    name: "WX wind vector E smooth"
    id: wx_wind_e_smooth
    accuracy_decimals: 3
    unit_of_measurement: ""
    filters:
      exponential_moving_average:
        alpha: 0.1
        send_every: 1
        send_first_at: 1
    
  - platform: template
    name: "WX wind direction smooth"
    id: wx_wind_dir_smooth
    accuracy_decimals: 1
    unit_of_measurement: "°"
    lambda: |-
      return -std::atan2(id(wx_wind_n_smooth).state, id(wx_wind_e_smooth).state) * 360 / 2 / std::numbers::pi;
    update_interval: 60s
        

sx127x:
  cs_pin: GPIO05
  rst_pin: GPIO26
  dio0_pin: GPIO36
  frequency: 433920000
  bandwidth: 50_0kHz
  modulation: OOK
  rx_start: true
  packet_mode: false
  bitsync: true
  bitrate: 4800
  rx_floor: -90

remote_receiver:
  - pin: GPIO13
    id: rf_A

rtl_433:
  id: rtl_A
  receiver_id: rf_A
  on_json_message:
    then:
      - lambda: |-
          if ((x["model"] == "Fineoffset-WHx080") && (x["id"].as<int>() == 87)) {
            id(wx_temperature).publish_state(x["temperature_C"].as<float>());
            id(wx_humidity).publish_state(x["humidity"].as<float>());
            id(wx_rain_total).publish_state(x["rain_mm"].as<float>());
            id(wx_rain_5min).publish_state(x["rain_mm"].as<float>());
            id(wx_rain_1h).publish_state(x["rain_mm"].as<float>());
            id(wx_rain_24h).publish_state(x["rain_mm"].as<float>());
            id(wx_wind_dir).publish_state(x["wind_dir_deg"].as<float>());
            id(wx_wind_avg).publish_state(x["wind_avg_km_h"].as<float>()*0.278);
            id(wx_wind_max).publish_state(x["wind_max_km_h"].as<float>()*0.278);
            id(wx_wind_n_smooth).publish_state(std::sin(-x["wind_dir_deg"].as<float>() / 360 * 2 * std::numbers::pi)); 
            id(wx_wind_e_smooth).publish_state(std::cos(-x["wind_dir_deg"].as<float>() / 360 * 2 * std::numbers::pi)); 
          }


lvgl:
  displays:
    - lcd_A
  pages:
    - !include
        file: page_wx.yaml
        vars:
          page_id: page_wx
          page_title: "Weather"


font:
  - file: "fonts/bdf/75dpi/helvR14.bdf"
    id: text_normal

  - file: "fonts/bdf/75dpi/helvB14.bdf"
    id: text_bold

  - file: "fonts/bdf/75dpi/helvB18.bdf"
    id: heading

  - file: "fonts/bdf/75dpi/helvR10.bdf"
    id: text_tiny

