# ESPHome configuration for M5S-0001
# Copyright © Stephen Irons 2026

# Hardware
# * M5Stack
# * LoRa433 module, modified with

substitutions:
  http_api_key1: !secret m5s-0001-tb_api_key


esphome:
  name: m5s-0001
  includes:
    - vc_version.h
    - build_details.h

  on_boot:
    then:
      - lambda: |-
          id(firmware_version).publish_state(FW_VERSION);
          id(build_ulid).publish_state(BUILD_ULID);
      - output.turn_on:
          id: lcd_bl
      - output.set_level:
          id: lcd_bl
          level: 100%


globals:
  - id: g_attributes_sent
    type: bool
    initial_value: 'false'

  - id: g_wx_telemetry_dirty
    type: bool
    initial_value: 'false'

  - id: g_wx_telemetry_blocked
    type: bool
    initial_value: 'false'


packages:
  core_hw: !include
    file: m5stack-core.yaml
    vars:
      invert_colors: true

  lps_hw: !include
    file: lps22.yaml
    vars:
      lps22_id: lps22_A
      lps22_name: LPS22.A
      lps22_i2c_addr: 0x5D

  rx_hw: !include
    file: m5stack-lora433-ook.yaml
    vars:
      rx_id: rx_A
      rx_name: RX.A
      rx_OOK_pin: GPIO13
      rx_frequency: 433920000

  wx: !include
    file: wx-433.yaml
    vars:
      wx_id: wx_A
      wx_name: WX.A
      rx_id: rx_A
      wx_tx_model: "Fineoffset-WHx080"
      wx_tx_id: 87

  fonts: !include
    file: fonts-m5stack.yaml


esp32:
  board: m5stack-core-esp32
  framework:
    type: esp-idf
#    sdkconfig_options:
#      CONFIG_MBEDTLS_CERTIFICATE_BUNDLE: y

#     type: arduino


# Enable logging
logger:


# Enable Home Assistant API
api:
  encryption:
    key: !secret m5s-0001-ha_api_key


ota:
  - platform: esphome
    password: !secret m5s-0001-ota_password


wifi:
  id: wifi1
  fast_connect: true
  enable_btm: true
  enable_rrm: true

  networks:
    - ssid: !secret wifi-1-ssid
      password: !secret wifi-1-psk

    - ssid: !secret wifi-2-ssid
      password: !secret wifi-2-ssid

  on_connect:
    then:
      - lvgl.label.update:
          id: page_wifi_value_state
          text: "Connected"

  on_disconnect:
    then:
      - lvgl.label.update:
          id: page_wifi_value_state
          text: "Disconnected"
      - lvgl.label.update:
          id: page_wifi_value_ssid
          text: " "
      - lvgl.label.update:
          id: page_wifi_value_rssi
          text: "--"
      - lvgl.label.update:
          id: page_wifi_value_ipaddr
          text: " "


debug:
  update_interval: 10s


time:
  - platform: homeassistant
    id: ha_time


http_request:
  timeout: 10s
  watchdog_timeout: 20s


text_sensor:
  - platform: template
    id: firmware_version
    name: "Firmware version"
    entity_category: diagnostic

  - platform: template
    id: build_ulid
    name: "Build ULID"
    entity_category: diagnostic

  - platform: wifi_info
    ip_address:
      name: "IP address"
      on_value:
        then:
          - lvgl.label.update:
              id: page_wifi_value_ipaddr
              text:
                format: "%s"
                args:
                  - x.c_str()

    ssid:
      name: "SSID"
      on_value:
        then:
          - lvgl.label.update:
              id: page_wifi_value_ssid
              text:
                format: "%s"
                args:
                  - x.c_str()

    mac_address:
      name: "MAC"
      on_value:
        then:
          - lvgl.label.update:
              id: page_wifi_value_macaddr
              text:
                format: "%s"
                args:
                  - x.c_str()


sensor:
  - id: !extend lps22_A
    pressure:
      on_value:
        then:
          - script.execute: wx_telemetry_trigger
          - lvgl.label.update:
              id: page_wx_value_pressure
              text:
                format: "%.1f"
                args:
                  - x

    temperature:
      on_value:
        then:
          - script.execute: wx_telemetry_trigger
          - lvgl.label.update:
              id: page_wx_value_temperature_int
              text:
                format: "%.1f"
                args:
                  - x


  # Temperature
  - id: !extend wx_temperature
    on_value:
      then:
        - script.execute: wx_telemetry_trigger
        - lvgl.label.update:
            id: page_wx_value_temperature
            text:
              format: "%.1f"
              args:
                - x

  # Humidity
  - id: !extend wx_humidity
    on_value:
      then:
        - script.execute: wx_telemetry_trigger
        - lvgl.label.update:
            id: page_wx_value_humidity
            text:
              format: "%.1f"
              args:
                - x

  # Rain
  - id: !extend wx_rain_total
    on_value:
      then:
        - script.execute: wx_telemetry_trigger
    #     - lvgl.label.update:
    #         id: page_wx_value_rain_total
    #         text:
    #           format: "%.1f"
    #           args:
    #             - x

  - id: !extend wx_rain_5min
    on_value:
      then:
        - script.execute: wx_telemetry_trigger
    #     - lvgl.label.update:
    #         id: page_wx_value_rain_5min
    #         text:
    #           format: "%.1f"
    #           args:
    #             - x

  - id: !extend wx_rain_1h
    on_value:
      then:
        - script.execute: wx_telemetry_trigger
        - lvgl.label.update:
            id: page_wx_value_rain_1h
            text:
              format: "%.1f"
              args:
                - x

  - id: !extend wx_rain_24h
    on_value:
      then:
        - script.execute: wx_telemetry_trigger
        - lvgl.label.update:
            id: page_wx_value_rain_24h
            text:
              format: "%.1f"
              args:
                - x

  # Wind speed
  - id: !extend wx_wind_avg
    on_value:
      then:
        - script.execute: wx_telemetry_trigger
        - lvgl.label.update:
            id: page_wx_value_wind_speed_m_s
            text:
              format: "%.1f"
              args:
                - x
        - lvgl.label.update:
            id: page_wx_value_wind_speed_kn
            text:
              format: "%.1f"
              args:
                - !lambda x * 1.944

  - id: !extend wx_wind_max
    on_value:
      then:
        - script.execute: wx_telemetry_trigger
        # - lvgl.label.update:
        #     id: page_wx_value_wind_max_m_s
        #     text:
        #       format: "%.1f"
        #       args:
        #         - x
        # - lvgl.label.update:
        #     id: page_wx_value_wind_max_kn
        #     text:
        #       format: "%.1f"
        #       args:
        #         - !lambda x * 1.944

  # Wind direction
  - id: !extend wx_wind_dir
    on_value:
      then:
        - script.execute: wx_telemetry_trigger
        # - lvgl.label.update:
        #     id: page_wx_value_wind_dir
        #     text:
        #       format: "%.1f"
        #       args:
        #         - x

  - id: !extend wx_wind_dir_smooth
    on_value:
      then:
        - script.execute: wx_telemetry_trigger
        - lvgl.label.update:
            id: page_wx_value_wind_dir
            text:
              format: "%.1f"
              args:
                - x


  # Wi-Fi
  - platform: wifi_signal
    name: "WiFi signal sensor"
    update_interval: 10s
    on_value:
      then:
        - lvgl.label.update:
            id: page_wifi_value_rssi
            text:
              format: "%.1f"
              args:
                - x

  - platform: debug
    free:
      name: "Heap free"
    fragmentation:
      name: "Heap fragmentation"
    block:
      name: "Heap max block"
    loop_time:
      name: "Loop time"


binary_sensor:
  - id: !extend btn_C
    on_press:
      then:
        - lvgl.page.next:


lvgl:
  displays:
    - lcd_A
  buffer_size: 8%
  pages:
    - !include
        file: page_wx.yaml
        vars:
          page_id: page_wx
          page_title: "Weather"

    - !include
        file: page_wifi.yaml
        vars:
          page_id: page_wifi
          page_title: "Wi-Fi"


script:
  - id: wx_telemetry_trigger
    then:
      - lambda: id(g_wx_telemetry_dirty) = true;
      - script.execute: wx_telemetry_send_throttled


  - id: wx_telemetry_send_throttled
    then:
      - logger.log: "Telemetry: evaluating"
      - if:
          condition:
            and:
              - lambda: 'return !id(g_wx_telemetry_blocked);'
              - lambda: 'return id(g_wx_telemetry_dirty);'
              - lambda: 'return id(wifi1).is_connected();'
              - lambda: 'return id(ha_time).now().is_valid();'
          then:
            - logger.log: "Telemetry: sending"
            - lambda: id(g_wx_telemetry_blocked) = true;
            - lambda: id(g_wx_telemetry_dirty) = false;
            - script.execute: wx_telemetry_send_now
            - logger.log: "Telemetry: sent"

            - if:
                condition:
                  lambda: 'return !id(g_attributes_sent);'
                then:
                  - logger.log: "Attributes: sent"
                  - script.execute: wx_attributes_send_now
                  - lambda: id(g_attributes_sent) = true;

            - delay: 60s
            - lambda: id(g_wx_telemetry_blocked) = false;
            - logger.log: "Telemetry: unblocked"
          else:
            - logger.log:
                format: "Telemetry: not sending: %d %d %d %d"
                args:
                  - 'id(g_wx_telemetry_blocked)'
                  - 'id(g_wx_telemetry_dirty)'
                  - 'id(wifi1).is_connected()'
                  - 'id(ha_time).now().is_valid()'


  - id: wx_telemetry_send_now
    then:
      - http_request.post:
          url: "https://iot.irons.nz/api/v1/${http_api_key1}/telemetry"
          request_headers:
            Content-Type: application/json
          json: !lambda |-
            root["ts"] = id(ha_time).now().timestamp * 1000ULL;
            JsonObject values = root["values"].to<JsonObject>();

            if (!isnan(id(wx_temperature).state))      values["temperature"]     = id(wx_temperature).state;
            if (!isnan(id(wx_humidity).state))         values["humidity"]        = id(wx_humidity).state;
            if (!isnan(id(wx_rain_total).state))       values["rain_total"]      = id(wx_rain_total).state;
            if (!isnan(id(wx_rain_5min).state))        values["rain_5min"]       = id(wx_rain_5min).state;
            if (!isnan(id(wx_rain_1h).state))          values["rain_1h"]         = id(wx_rain_1h).state;
            if (!isnan(id(wx_rain_24h).state))         values["rain_24h"]        = id(wx_rain_24h).state;
            if (!isnan(id(wx_wind_avg).state))         values["wind_avg"]        = id(wx_wind_avg).state;
            if (!isnan(id(wx_wind_max).state))         values["wind_max"]        = id(wx_wind_max).state;
            if (!isnan(id(wx_wind_dir).state))         values["wind_dir"]        = id(wx_wind_dir).state;
            if (!isnan(id(wx_wind_n_smooth).state))    values["wind_n_smooth"]   = id(wx_wind_n_smooth).state;
            if (!isnan(id(wx_wind_e_smooth).state))    values["wind_e_smooth"]   = id(wx_wind_e_smooth).state;
            if (!isnan(id(wx_wind_dir_smooth).state))  values["wind_dir_smooth"] = id(wx_wind_dir_smooth).state;
            if (!isnan(id(wx_pressure).state))         values["pressure"]        = id(wx_pressure).state;
            if (!isnan(id(wx_temperature_int).state))  values["temperature_int"] = id(wx_temperature_int).state;


  - id: wx_attributes_send_now
    then:
      - http_request.post:
          url: "https://iot.irons.nz/api/v1/${http_api_key1}/attributes"
          request_headers:
            Content-Type: application/json
          json: !lambda |-
            root["fw_version"] = id(firmware_version).state;
            root["build_ulid"] = id(build_ulid).state;
