esphome:
  name: m5stack-1

packages:
    rtl_433: github://juanboro/esphome-rtl_433-decoder/rtl_433.yaml

esp32:
  board: m5stack-core-esp32
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_psk


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: Button A
    id: btn_A
    
  - platform: gpio
    pin:
      number: GPIO38
      inverted: true
    name: Button B
    id: btn_B
    
  - platform: gpio
    pin:
      number: GPIO37
      inverted: true
    name: Button C
    id: btn_C

spi:
  - clk_pin: GPIO18
    mosi_pin: GPIO23
    miso_pin: GPIO19
    id: spi_A
    
i2c:
  - sda: GPIO21
    scl: GPIO22
    scan: true
    id: i2c_a
    
sensor:
  - platform: lps22
    address: 0x5D
    temperature:
      name: "LPS22 temperature"
    pressure:
      name: "LPS22 pressure"

  - platform: template
    name: "WX temperature"
    id: wx_temperature_C
    unit_of_measurement: "°C"
    
    
sx127x:
  cs_pin: GPIO05
  rst_pin: GPIO26
  dio0_pin: GPIO36
  frequency: 433920000
  bandwidth: 50_0kHz
  modulation: OOK
  rx_start: true
  packet_mode: false
  bitsync: true
  bitrate: 4800
  rx_floor: -90

remote_receiver:
  - pin: GPIO13
#    dump: all
    id: rf_A

rtl_433:
  id: rtl_A
  receiver_id: rf_A
  on_json_message:
    then:
      - lambda: |-
          if ((x["model"] == "Fineoffset-WHx080") && (x["id"].as<int>() == 87)) {
            id(wx_temperature_C).publish_state(x["temperature_C"].as<float>());
          }
        
