# Version and build details
# Copyright © Stephen Irons 2026

PRODUCT := $(PRODUCT)
DEVICE := /dev/serial/by-id/usb-Silicon_Labs_CP2104_USB_to_UART_Bridge_Controller_01EDB825-if00-port0

BUILD_DIR := .
ESPHOME_BIN := ../esphome-dev/venv/bin/esphome


compile:

# Build properties
BUILD_START := $(shell date +%s.%3N)
BUILD_DATE := $(shell date +"%Y-%m-%d %H:%M:%S%z" -d @$(BUILD_START))
BUILD_UUID := $(shell uuidgen)
BUILD_ULID := $(shell .venv/bin/python3 -c 'import ulid; print(ulid.from_timestamp($(BUILD_START)))')
BUILD_ID := $(shell touch ~/.build-id ; echo $$(( $$(cat ~/.build-id) + 1)) > ~/.build-id ; cat ~/.build-id )
BUILD_USERNAME := $(USERNAME)
BUILD_HOSTNAME := $(shell hostname)

# Versions
VC_VERSION := $(shell git status > /dev/null; git describe --tags --exact-match 2>/dev/null || echo "g`git rev-parse --short=8 HEAD`")$(shell git diff-index --exit-code --name-status HEAD >/dev/null || echo "-dirty")
VC_BRANCH_VERSION := $(shell git status > /dev/null; git describe --tags --exact-match 2>/dev/null || echo "`git branch --show-current`-g`git rev-parse --short=8 HEAD`")$(shell git diff-index --exit-code --name-status HEAD >/dev/null || echo "-dirty")

FW_VERSION := $(VC_VERSION).$(BUILD_ID)

vc-version: $(BUILD_DIR)/vc_version.h $(BUILD_DIR)/build_details.h
	@echo $(FW_VERSION)
.PHONY: vc-version

echo-vc-version:
	@echo $(FW_VERSION)
.PHONY: echo-vc-version

$(BUILD_DIR)/vc_version.h: Makefile
	@rm -f $@.tmp
	@echo "// DO NOT EDIT" >> $@.tmp
	@echo "// Autogenerated from recipe in Makefile" >> $@.tmp
	@echo "" >> $@.tmp
	@echo "#define FW_VERSION \"$(FW_VERSION)\"" >> $@.tmp
	@echo "#define VC_VERSION \"$(VC_VERSION)\"" >> $@.tmp
	@echo "#define HW_PLATFORM \"$(HW_PLATFORM)\"" >> $@.tmp
	@diff -N --unchanged-line-format '' --old-line-format '-%L' --new-line-format '+%L' $@ $@.tmp || mv $@.tmp $@
	@rm -f $@.tmp
.PHONY: $(BUILD_DIR)/vc_version.h

$(BUILD_DIR)/build_details.h: Makefile
	@rm -f $@.tmp
	@echo "// DO NOT EDIT" >> $@.tmp
	@echo "// Autogenerated from recipe in Makefile" >> $@.tmp
	@echo "" >> $@.tmp
	@echo "#define BUILD_DATE \"$(BUILD_DATE)\"" >> $@.tmp
	@echo "#define BUILD_ULID \"$(BUILD_ULID)\"" >> $@.tmp
	@echo "#define BUILD_ID \"$(BUILD_ID)\"" >> $@.tmp
	@echo "#define BUILD_MACHINE \"$(BUILD_HOSTNAME)\"" >> $@.tmp
	@diff -N --unchanged-line-format '' --old-line-format '-%L' --new-line-format '+%L' $@ $@.tmp || mv $@.tmp $@
	@rm -f $@.tmp
.PHONY: $(BUILD_DIR)/build_details.h


compile: $(PRODUCT).yaml vc-version
	$(ESPHOME_BIN) compile $<
.PHONY: compile

run: $(PRODUCT).yaml vc-version
	$(ESPHOME_BIN) run $< --device $(DEVICE)
.PHONY: run

