# ESPHome configuration for M5S-0001
# Copyright © Stephen Irons 2026

# Hardware
# * Arlec Grid Connect Smart Plug
# * BK72xx CB2S


substitutions:
  device_id: sw-0011
  device_name: SW-0011
  device_manufacturer: Ironspark
  device_part_number: 99-9002-0011-00
  device_model: PC191 HA Series 3
  device_serial: 99-9005-0001
  device_uart: "/dev/serial/by-id/usb-Silicon_Labs_CP2104_USB_to_UART_Bridge_Controller_01EDB825-if00-port0"
  device_ipaddr: "192.168.1.131"
  device_hostname: sw-0011
  device_uuid: 24caf015-0d63-462f-ad58-14e8d1951353

  ha_api_key: !secret sw-0011-ha_api_key
  ota_password: !secret sw-0011-ota_password
  ap_ssid: !secret sw-0011-ap_ssid
  ap_psk: !secret sw-0011-ap_psk
  tb_api_key: !secret sw-0011-tb_api_key

  bl0937_voltage_divider: "750"
  bl0937_current_resistor: "0.0025 ohm"


esphome:
  name: ${device_id}
  friendly_name: ${device_name}

bk72xx:
  board: cb2s


api:
  encryption:
    key: ${ha_api_key}


ota:
  - platform: esphome
    password: ${ota_password}


logger:


packages:
  # TODO: include hardware details
  # core_hw: !include
  #   file: hw/pc191-ha-series-3.yaml

  firmware_details: !include
    file: shared/firmware_details.yaml

  # debug-heap is not available on BK72xx
  # debug_heap: !include
  #   file: shared/debug-heap.yaml

  wifi: !include
    file: shared/wifi.yaml


# The main relay is connected to P26
switch:
  - platform: gpio
    name: Socket
    pin: P8  # was P26 on series 2
    id: socket1
    on_turn_on:
      then:
        light.turn_on: led1
    on_turn_off:
      then:
        light.turn_off: led1


# The button on the side of the socket is wired to P11
binary_sensor:
  - platform: gpio
    pin:
      number: P11
      mode:
        input: true
        pullup: true
      inverted: true
    name: Button
    on_click:
      min_length: 50ms
      then:
        switch.toggle: socket1


# The LED is directly controlled via the state of the relay with the switch above
light:
  - platform: binary
    name: "LED"
    id: led1
    output: light_output
    internal: true

output:
  - id: light_output
    platform: gpio
    inverted: false  # was 'true' on Series 2
    pin: P26   # was P8 on Series 2


# The pins were checked with a multimeter and the datasheet for the built in BL0937.
sensor:
  - platform: internal_temperature
    name: "Internal Temperature"

  - platform: hlw8012
    model: BL0937
    cf_pin:
      number: P7
      inverted: true
    cf1_pin:
      number: P6
      inverted: true
    sel_pin:
      number: P24
      inverted: true
    current:
      name: BL0937 Current
    voltage:
      name: BL0937 Voltage
    power:
      name: BL0937 Power
    energy:
      name: BL0937 Energy
    voltage_divider: $bl0937_voltage_divider
    current_resistor: $bl0937_current_resistor
    update_interval: 15s
    change_mode_every: 4

