# ESPHome application definition
# Copyright © Stephen Irons 2026

# Uses rtl-433 component
# * Receives 433 MHz data from weather module
# * Decodes to JSON
# * Publishes various JSON values to 'sensors'


packages:
  rtl_433: github://juanboro/esphome-rtl_433-decoder/rtl_433.yaml


rtl_433:
  id: ${wx_id}
  receiver_id: ${rx_id}

  on_json_message:
    then:
      - if:
          condition:
            lambda: |-
              return (x["model"] == "${wx_tx_model}") && (x["id"].as<int>() == ${wx_tx_id});
          then:
              # Update template sensors
            - lambda: |-
                id(wx_temperature).publish_state(x["temperature_C"].as<float>());
                id(wx_humidity).publish_state(x["humidity"].as<float>());
                id(wx_rain_total).publish_state(x["rain_mm"].as<float>());
                id(wx_rain_5min).publish_state(x["rain_mm"].as<float>());
                id(wx_rain_1h).publish_state(x["rain_mm"].as<float>());
                id(wx_rain_24h).publish_state(x["rain_mm"].as<float>());
                id(wx_wind_avg).publish_state(x["wind_avg_km_h"].as<float>()*0.278);
                id(wx_wind_max).publish_state(x["wind_max_km_h"].as<float>()*0.278);
                id(wx_wind_dir).publish_state(x["wind_dir_deg"].as<float>());
                id(wx_wind_n).publish_state(std::sin(-x["wind_dir_deg"].as<float>() / 360 * 2 * std::numbers::pi) * x["wind_avg_km_h"].as<float>()*0.278);
                id(wx_wind_e).publish_state(std::cos(-x["wind_dir_deg"].as<float>() / 360 * 2 * std::numbers::pi) * x["wind_avg_km_h"].as<float>()*0.278);


sensor:
  # Temperature
  - platform: template
    id: wx_temperature
    name: "Temperature"
    accuracy_decimals: 1
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"

  # Humidity
  - platform: template
    id: wx_humidity
    name: "Humidity"
    accuracy_decimals: 1
    unit_of_measurement: "%RH"
    icon: "mdi:water-percent"

  # Rain
  - platform: template
    id: wx_rain_total
    name: "Rain total"
    accuracy_decimals: 1
    unit_of_measurement: "mm"
    icon: "mdi:water"

  - platform: template
    id: wx_rain_5min
    name: "Rain_5min"
    accuracy_decimals: 1
    unit_of_measurement: "mm"
    icon: "mdi:water"
    filters:
      - heartbeat: 30s
      - delay_delta:
          window_size: 10

  - platform: template
    id: wx_rain_1h
    name: Rain 1h"
    accuracy_decimals: 1
    unit_of_measurement: "mm"
    icon: "mdi:water"
    filters:
      - heartbeat: 5min
      - delay_delta:
          window_size: 12

  - platform: template
    id: wx_rain_24h
    name: "Rain 24h"
    accuracy_decimals: 1
    unit_of_measurement: "mm"
    icon: "mdi:water"
    filters:
      - heartbeat: 5min
      - delay_delta:
          window_size: 288

  # Wind speed
  - platform: template
    id: wx_wind_avg
    name: "Wind speed average"
    accuracy_decimals: 1
    unit_of_measurement: "m.s-1"
    icon: "mdi:weather-windy"
    filters:
      exponential_moving_average:
        alpha: 0.05
        send_every: 1
        send_first_at: 1


  - platform: template
    id: wx_wind_max
    name: "Wind speed max"
    accuracy_decimals: 1
    unit_of_measurement: "m.s-1"
    icon: "mdi:weather-windy"
    filters:
      exponential_moving_average:
        alpha: 0.05
        send_every: 1
        send_first_at: 1


  # Wind direction
  - platform: template
    id: wx_wind_dir
    name: "Wind direction"
    accuracy_decimals: 1
    unit_of_measurement: "°"
    icon: "mdi:compass"

  - platform: template
    id: wx_wind_n
    internal: true
    accuracy_decimals: 3
    unit_of_measurement: "m.s-1"
    filters:
      exponential_moving_average:
        alpha: 0.05
        send_every: 1
        send_first_at: 1

  - platform: template
    id: wx_wind_e
    internal: true
    accuracy_decimals: 3
    unit_of_measurement: "m.s-1"
    filters:
      exponential_moving_average:
        alpha: 0.05
        send_every: 1
        send_first_at: 1

  - platform: template
    id: wx_wind_dir_smooth
    name: "Wind direction smooth"
    accuracy_decimals: 1
    unit_of_measurement: "°"
    icon: "mdi:compass"
    lambda: |-
      float dir = -std::atan2(id(wx_wind_n).state, id(wx_wind_e).state) * 360 / 2 / std::numbers::pi;
      return std::fmod(dir + 360, 360);
    update_interval: 60s
    filters:
      - filter_out: NAN

  - platform: template
    id: wx_wind_avg_smooth
    name: "Wind speed smooth"
    accuracy_decimals: 1
    unit_of_measurement: "m.s-1"
    icon: "mdi:weather-windy"
    lambda: |-
      float avg = std::sqrt(std::pow(id(wx_wind_n).state, 2) + std::pow(id(wx_wind_e).state, 2));
      return avg;
    update_interval: 60s
    filters:
      - filter_out: NAN
