sensor:
  - platform: lps22
    id: ${lps22_id}
    i2c_id: ${lps22_i2c_bus}
    address: ${lps22_i2c_addr}

    pressure:
      id: wx_pressure
      name: "Pressure"
      accuracy_decimals: 1

    temperature:
      id: wx_temperature_int
      name: "Temperature int"
      accuracy_decimals: 1
