# ESPHome configuration: shared wifi
# Copyright © Stephen Irons 2026

wifi:
  id: wifi1
  fast_connect: true

  # BTM and RRM are not supported on BK72xx
  # They are optional, and not really needed as the devices are stationary and have good signal strength.
  # TODO: enable on ESP32, not on BK72xx

  # enable_btm: true
  # enable_rrm: true

  networks:
    - ssid: !secret wifi-1-ssid
      password: !secret wifi-1-psk

    - ssid: !secret wifi-2-ssid
      password: !secret wifi-2-psk


sensor:
  - platform: wifi_signal
    name: WiFi Level
    id: wifi_dBm
    update_interval: 30s


text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP address"
      id: wifi_ipaddr

    ssid:
      name: "SSID"
      id: wifi_ssid

    mac_address:
      name: "MAC"
      id: wifi_mac
